name: main_feed
description: Generates main feed
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  dart_appwrite: 11.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
